[settings]
;https://github.com/jaagr/polybar/wiki/Configuration#application-settings
screenchange-reload = true

; Enables pseudo-transparency for the bar
; If set to true the bar can be transparent without a compositor.
pseudo-transparency = true
compositing-background = over
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

; Define fallback values used by all module formats
format-foreground = #FF0000
format-background = #00FF00

include-file = ~/.config/bspwm/polybar/themes/colors/gruvbox.ini
include-file = modules.ini

[bar/cliffmain]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false
width = 100%
height = 18.75pt
;previous value for radius was 10%
radius = 0
bottom = false
fixed-center = true
scroll-up = bspwm.next
scroll-down = bspwm.prev

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt
line-color = ${colors.foreground}

border-size = 0
border-color = ${colors.darkgreen}

padding-left = 6px
padding-right = 6px

module-margin-left = 5px
module-margin-right = 5px

offset-x = 0
offset-y = 0

; separator = |
separator-foreground = ${colors.darkorange}

font-0 = "JetBrainsMono NF:style=Medium:size=10;2"
font-1= "Symbols Nerd Font Mono:size=10;2"
font-2 = "Koruri:size=10;2"
font-3 = "Material Design Icons Desktop:size=10;3"
font-4 = "Font Awesome 6 Free Solid:size=10;2"
font-5 = "Material Design Icons Desktop:size=11;3"

modules-left = bspwm xwindow mpd
modules-center = date
modules-right = tray bluetooth pulseaudio backlight cpu_bar temperature battery

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = false
wm-name = bspwm
locale = es_AR.UTF-8
wm-restack = bspwm
