final_space = true
version = 2

[transient_prompt]
background = "transparent"
foreground = "#d8dee9"
template = "<#5e81ac>╺[</><#88c0d0>{{ .Folder }}</><#5e81ac>]</>{{ if .Root }}<#5e81ac>[</>\uf0e7<#5e81ac>]</>{{ end }}{{ if ne .Code 0 }}<#5e81ac>[x</><#b48ead>{{ .Code }}</><#5e81ac>]</>{{ end }} <#5e81ac>\ue602</> "

[[blocks]]
alignment = "left"
type = "prompt"

[[blocks.segments]]
foreground = "#88c0d0"
style = "plain"
template = "<#5e81ac>┏[</>{{ .UserName }}<#5e81ac>]</>"
type = "session"

[[blocks.segments]]
foreground = "#b48ead"
style = "plain"
template = "<#5e81ac>--[</>{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}<#8fbcbb> ● </>{{ end }}{{ if .Staging.Changed }}<#88c0d0> ● </>{{ end }}<#5e81ac>]</>"
type = "git"

[blocks.segments.options]
fetch_status = true
fetch_upstream_icon = true

[[blocks.segments]]
type = "lua"
style = "plain"
foreground = "#5e81ac"
template = " {{ .Full }}"

[[blocks.segments]]
type = "node"
style = "plain"
foreground = "#88c0d0"
template = " {{ .Full }}"

[[blocks.segments]]
type = "vimode"
style = "plain"
# foreground = "#d8dee9"
foreground = "#b48ead"
template = "{{ if eq .Mode \"normal\" }} NORMAL{{ else if eq .Mode \"visual\" }} VISUAL{{ else }} INSERT{{ end }}"

[[blocks.segments]]
foreground = "#d8dee9"
style = "plain"
template = "<#5e81ac>[</>\uf0e7<#5e81ac>]</>"
type = "root"

[[blocks.segments]]
foreground = "#d8dee9"
style = "plain"
template = "<#5e81ac>[x</>{{ reason .Code }}<#5e81ac>]</>"
type = "status"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

[[blocks.segments]]
foreground = "#88c0d0"
style = "plain"
template = "<#5e81ac>└[</>{{ .Path }}<#5e81ac>]</>"
type = "path"

[blocks.segments.options]
style = "full"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

[[blocks.segments]]
foreground = "#5e81ac"
style = "plain"
template = " \ue602 "
type = "text"
