clipboard_control write-clipboard read-clipboard

# temas
include GruvBox_DarkHard.conf
#include Wryan.conf
#include VSCode_Dark.conf

# opacidad y efecto borroso del fondo
background_opacity 1.0
background_blur 1

# avanzado
term xterm-kitty

# sonido de la campana
enable_audio_bell no

# ajustes específicos del SO (decoración de ventana Gnome para Wayland)
linux_display_server x11
# linux_display_server wayland

# fuente
font_family        JetBrainsMono Nerd Font Mono
bold_font          auto
italic_font        auto
bold_italic_font   auto
font_size 11.0

# administración del tamaño de la fuente
map ctrl+shift+backspace change_font_size all 0

# personalización del cursor
# bloque / rayo / subrayado
cursor_shape block
cursor_blink_interval 1
cursor_stop_blinking_after 0
shell_integration no-cursor

# historial de desplazamiento
scrollback_lines 5000
wheel_scroll_multiplier 3.0

# ratón
mouse_hide_wait -1

# diseño de la ventana
remember_window_size  yes
initial_window_width  1200
initial_window_height 750
window_border_width 1.5pt
enabled_layouts tall
window_padding_width 0
window_margin_width 2
hide_window_decorations no

# administración de ventanas
map ctrl+shift+enter new_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window

# administración de diseños
# map ctrl+shift+l next_layout
# map ctrl+alt+r goto_layout tall
# map ctrl+alt+s goto_layout stack

# personalización de la barra de pestañas
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge bottom
tab_bar_align left
active_tab_font_style   bold
inactive_tab_font_style normal

# administración de pestañas
# map ctrl+shift+t new_tab
# map ctrl+shift+right next_tab
# map ctrl+shift+left previous_tab
# map ctrl+shift+q close_tab
