#!/bin/bash
draw() {
    kitten icat --stdin no --transfer-mode memory --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
    exit 1
}

drawpdf() {
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "/tmp/$filename.png" </dev/null >/dev/tty
    exit 1
}

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

# filename=$(basename $(echo "$file" | tr ' ' '_'))
type=$(file -Lb --mime-type "$file" | cut -d/ -f2)
filename=$(basename -s ".$type" "$file")

case "$(file -Lb --mime-type "$file")" in
image/*)
    draw "$file"
    ;;
video/*)
    # vidthumb is from here:
    # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
    draw "$(vidthumb "$file")"
    ;;
# Very fucking autistic way of doing previews with just kitty and pdftoppm, but it works
# God thank this guy for existing:
# https://www.reddit.com/r/KittyTerminal/comments/132n4p5/any_lf_file_manager_users_how_to_preview_pdfs_as/
# if [[ "$(file -Lb --mime-type "$file")" =~ ^application/pdf ]]; then

application/pdf)
    if [[ ! -f "/tmp/$filename.png" ]]; then
        pdftoppm -f 1 -l 1 "$file" >>"/tmp/$filename.png"
    fi
    drawpdf
    ;;
application/epub+zip)
    if [[ ! -f "/tmp/$filename.png" ]]; then
        gnome-epub-thumbnailer "$file" "/tmp/$filename.png"
    fi
    drawpdf
    ;;
esac

pistol "$file"
