#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias v="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# so, aliases for some programs are here, as follows:

# youtube-dl
alias \
    yt='yt-dlp --embed-thumbnail --embed-metadata --add-metadata -i' \
    yta='yt -x -f bestaudio/best -o "~/Musica/dl-music/%(title)s.%(ext)s"' \
    ytp='yt -x -f bestaudio/best -o "~/Videos/Podcast/%(title)s.%(ext)s"' \
    ytn='yt --embed-thumbnail --embed-metadata -o "./%(title)s.%(ext)s"'

# Expand sudo to work with aliases
alias sudo="sudo "

# Verbosity and settings that you pretty much just always are going to want.
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    mkd="mkdir -pv" \
    rmd="rmdir -v" \
    du="du -h" \
    lf="lfrun" \
    rs="rsync -Pav" \
    rnew="rs -Pav -z --update --delete-after" \
    fm="pcmanfm > /dev/null 2>&1 &" \
    texwatch="latexmk -pdf -pvc" # better latex compiler

# ffmpeg commands
alias \
    ffmpeg="ffmpeg -hide_banner" \
    ffconvert='find -maxdepth 1 -mindepth 1 -type f -name "*.mkv" -print -exec sh -c '\''i="{}"; ffmpeg -i "$i" -c:v libx264 -crf 22 "${i%.mkv}".mp4'\'' \;' \
    tothumbnail='ffmpeg -loop 1 -i $1 -i $2 c:v libx265 -c:a aac -b:a 320k -pix_fmt yuv420p -shortest out.mp4'

# These common commands are just too long! Abbreviate them.
# i="imv -u linear" \
alias \
    z="zathura" \
    ka="killall" \
    g="git status" \
    gm="git commit -m" \
    gp="git push" \
    gb="git branch" \
    gic="git checkout" \
    i="nsxiv -q -a -t" \
    sdn="shutdown -h now" \
    df='df -lH ' \
    f="fastfetch" \
    h="htop" \
    c="cointop" \
    b="$EDITOR ~/.config/hypr/modules/binds.conf" \
    pcopy="pwd | wl-copy --trim-newline" \
    src="source ~/.zshrc && echo 'sourceado nwn!'"

# Pacman
alias \
    p="pacman" \
    pn="pacman -S --needed" \
    pu="pacman -Syu"

# tmux commands
alias \
    tn="tmux-sessionizer.sh" \
    tk="tmux kill-session"

# enable color support of ls and also add handy aliases
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    cat="bat --theme=base16" \
    dt='ls -l | grep "$(if [[ "$(date "+%-d")" -lt 10 ]]; then date "+%b  %-d"; else date "+%b %-d"; fi)"' \
    dir="dir --color=auto" \
    vdir="vdir --color=auto" \
    grep="grep --color=auto" \
    fgrep="fgrep --color=auto" \
    egrep="egrep --color=auto" \
    diff="diff --color=auto" \
    fc-list="fc-list -f '%{file}\n'" \
    ip="ip --color=auto"

# Mpv
alias podcast="mpv --no-video"
alias serie="mpv list.m3u8 > /dev/null 2>&1"

con() {
    cd ~/.config || exit
    selected_file=$(fzf --color="16") || return # Return if no selection
    cd "$(dirname "$selected_file")" || exit
    $EDITOR "$(basename "$selected_file")" # Open the file
}

se() {
    cd ~/.local/bin || exit
    $EDITOR "$(fzf)"
}
