screenshot-directory=~/Escritorio/mpv
save-position-on-quit
sub-auto=fuzzy

profile=high-quality

vo=gpu-next
gpu-api=vulkan
hwdec=auto # enable best HW decoder; turn off for software decoding

# Additional Vulkan settings
# vulkan-async-compute=yes
# vulkan-async-transfer=yes
# vulkan-queue-count=1
# vd-lavc-dr=yes

reset-on-next-file=audio-delay,mute,pause,speed,sub-delay,video-aspect-override,video-pan-x,video-pan-y,video-rotate,video-zoom,volume

display-fps-override=60
video-sync=display-resample
interpolation=yes
tscale=oversample # smoothmotion

deband=yes # enabled by default
deband-iterations=4 # deband steps
deband-threshold=35 # deband strength
deband-range=16 # deband range
deband-grain=5 # dynamic grain: set to "0" if using the static grain shader

# Enable IPC support to control mpv from the command line
# input-ipc-server=/tmp/mpv-socket
