[main]
include=/usr/share/foot/themes/gruvbox-dark
font=Fira Code:size=11
pad=15x15
term=foot

[colors]
alpha=0.85

## Sixel colors
sixel0 =  000000
sixel1 =  3333cc
sixel2 =  cc2121
sixel3 =  33cc33
sixel4 =  cc33cc
sixel5 =  33cccc
sixel6 =  cccc33
sixel7 =  878787
sixel8 =  424242
sixel9 =  545499
sixel10 = 994242
sixel11 = 549954
sixel12 = 995499
sixel13 = 549999
sixel14 = 999954
sixel15 = cccccc

[key-bindings]
font-increase=Control+Shift+k
font-decrease=Control+Shift+j
search-start=Control+Shift+f
clipboard-copy=Control+c
clipboard-paste=Control+v
scrollback-up-half-page=Control+k
scrollback-down-half-page=Control+j
show-urls-launch=Control+Shift+l
