general {
    lock_cmd = pidof swaylock || swaylock -f
    before_sleep_cmd = swaylock -f
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 180                                # 3min
    on-timeout = brillo -O && brillo -S 10.0
    on-resume = brillo -I
}

listener {
    timeout = 420                                 # 7min
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' && swaylock -f
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
