general {
    lock_cmd = pidof swaylock || swaylock -f
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}


listener {
    timeout = 290
    on-timeout = brillo -O
}


listener {
    timeout = 300                                # 5min
    on-timeout = brillo -S 15.0
    on-resume = brillo -I
}

listener {
    timeout = 600                                 # 10min
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' && loginctl lock-session
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
