background {
    monitor =
    path = screenshot
    color = rgba(25, 20, 20, 1.0)
    noise = 0.05
    contrast = 0.5
    vibrancy = 0.5
    vibrancy_darkness = 0.1
    blur_passes = 2
}

# shape {
#     monitor =
#     size = 180, 60
#     border_size = 2
#     rounding = 100
#     color = rgba(ddc7a1aa)
#     border_color = rgb(6c782e)
#     position = 0, 80
#     halign = center
#     valign = center
# }

input-field {
    monitor =
    placeholder_text = <i>Intenta desbloquearme nwn</i>
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    dots_size = 0.15

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color=rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg
    font_family = Ubuntu

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center

    capslock_color = rgb(6c782e) rgba(e78a4eee) rgba(c14a4abb) 45deg
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%A %e %B %Y %R:%S')"
    color = rgba(ddc7a1aa)
    font_size = 20
    font_size = Inconsolata
    position = 0, 200
}
