background {
    monitor =
    path = screenshot
    color = rgba(25, 20, 20, 1.0)
    noise = 0.05
    contrast = 0.5
    vibrancy = 0.5
    vibrancy_darkness = 0.1
    blur_passes = 2
}

input-field {
    monitor =
    placeholder_text = <b>Intenta desbloquearme nwn</b>
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    dots_size = 0.15

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color=rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_text = <b>"QUE HACE MALONGO? DEBLOQUEAME BIEN NWNWNWN"</b>
    fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg
    fail_transition = 300 # transition time in ms between normal outer_color and fail_color
    font_family = Ubuntu

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center

    capslock_color = rgb(6c782e) rgba(e78a4eee) rgba(c14a4abb) 45deg
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%A %e %B %Y %R:%S')"
    color = rgba(ddc7a1aa)
    font_size = Libertinus Sans
    font_size = 20
    position = 0, 200
}
