preload = /home/utane/Imagenes/walls/hyperborea/34209-3065x1909-desktop-hd-the-lord-of-the-rings-background-image.jpg
wallpaper = ,/home/utane/Imagenes/walls/hyperborea/34209-3065x1909-desktop-hd-the-lord-of-the-rings-background-image.jpg
