################
### MONITORS ###
################

monitor=,preferred,auto,auto

###################
### MY PROGRAMS ###
###################

# Set programs that you use
$terminal = foot
$fileManager = pcmanfm
$menu = rofi -show combi -combi-modes "drun,ssh" -modes combi

source = ~/.config/hypr/modules/autostart.conf

source = ~/.config/hypr/modules/animations-optimized.conf

# unscale XWayland
xwayland {
  enabled = true
  force_zero_scaling = true
  create_abstract_socket = true
}

###################
### PERMISSIONS ###
###################

# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

ecosystem {
  enforce_permissions = false
}

permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow


#####################
### LOOK AND FEEL ###
#####################

source = ~/.config/hypr/modules/look.conf

#############
### INPUT ###
#############
source = ~/.config/hypr/modules/input.conf

###################
### KEYBINDINGS ###
###################
source = ~/.config/hypr/modules/binds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

source = ~/.config/hypr/modules/windows.conf

# Logs
debug {
disable_logs = false
}
