input {
    kb_layout = latam
    # kb_variant = ,latam
    kb_model = dell
    kb_options = caps:swapescape,altwin:menu_win
    numlock_by_default = true
    # kb_rules =

    # Delay before a held-down key is repeated, in milliseconds.
    repeat_delay = 300
    repeat_rate = 50

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        tap-and-drag = true
        clickfinger_behavior = true
        tap-to-click = true
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = false
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
