# Tags
windowrule = tag +video, match:class mpv

windowrule = tag +img, match:class Nsxiv

# PDF
windowrule = tag +pdf, match:class org.pwmt.zathura

# Browser
windowrule = tag +browser, match:class firefox-esr
windowrule = tag +browser, match:class firefox
windowrule = tag +browser, match:class librewolf
windowrule = tag +browser, match:class brave-browser

# GUI
windowrule = tag +gui, match:class blueberry.py
windowrule = tag +gui, match:class ^(calibre).*$
windowrule = tag +gui, match:class code
windowrule = tag +gui, match:class GeoGebra
windowrule = tag +gui, match:class pcmanfm-qt
windowrule = tag +gui, match:class pcmanfm
windowrule = tag +gui, match:class .*(fcitx5-config-qt)$
windowrule = tag +gui, match:class org.pulseaudio.pavucontrol
windowrule = tag +gui, match:class ^(com\.obsproject\.Studio)$
windowrule = tag +gui, match:class gimp
windowrule = tag +gui, match:class org.nicotine_plus.Nicotine
windowrule = tag +gui, match:class steam
windowrule = tag +gui, match:class xdg-desktop-portal-gtk
windowrule = tag +gui, match:class virt-manager
windowrule = tag +gui, match:class filezilla

#Float
windowrule = match:class mpv, match:float true
windowrule = center on, match:class mpv
windowrule = match:content video, match:class mpv
windowrule = match:float true, match:tag gui

# Sizes
# windowrule = maxsize 849 477, match:class mpv
# windowrule = maxsize 849 477, tag:img
windowrule = match:float true, match:tag img

# Opacity and blur
windowrule = no_blur on, match:class mpv
windowrule = no_blur on, match:tag img
windowrule = opacity 1.0 override, match:tag img
windowrule = opacity 1.0 override, match:tag video
windowrule = opacity 1.0 override, match:class .*(KeePassXC)$
windowrule = no_blur true, match:tag browser
windowrule = opacity 1.0 override, match:tag browser
windowrule = opacity 1.0 override, match:tag gui
windowrule = opacity 1.0 override, match:tag pdf
windowrule = opacity 1.0 override, match:title ^(Transmission)$

# Workspaces

# Workspace 1
windowrule = workspace 1, match:class firefox-esr
windowrule = workspace 1, match:class firefox

# Worspace 3
windowrule = workspace 3, match:class brave-browser

# Workspace 4
windowrule = workspace 4, match:class code
windowrule = workspace 4, match:class ^(VirtualBox)
windowrule = workspace 4, match:class ^(virt-manager)

# Workspace 5
windowrule = workspace 5, match:class .*(KeePassXC)$

# Workspace 6
windowrule = workspace 6, match:class gimp
windowrule = workspace 6, match:class filezilla

# Workspace 7
windowrule = workspace 7, match:class ^(com\.obsproject\.Studio)$

# Workspace 8
windowrule = workspace 8 silent, match:class org.nicotine_plus.Nicotine
windowrule = workspace 8 silent float, match:class steam

# Workspace 10
windowrule = workspace 10 silent, match:title ^(Transmission)$
