# Tags
windowrule = tag +video, match:class mpv
windowrule = tag +img, match:class Nsxiv
windowrule = tag +pdf, match:class ^.*(zathura)$
windowrule = tag +browser, match:class firefox
windowrule = tag +browser, match:class brave-browser
windowrule = tag +browser, match:class librewolf

# GUI
windowrule = tag +gui, match:class ^(blue).*$
windowrule = tag +gui, match:class ^(calibre).*$
windowrule = tag +gui, match:class gcr-prompter
windowrule = tag +gui, match:class code
windowrule = tag +gui, match:class GeoGebra
windowrule = tag +gui, match:class ^(pcmanfm).*$
windowrule = tag +gui, match:class .*(fcitx5-config-qt)$
windowrule = tag +gui, match:class ^.*(pavucontrol)$
windowrule = tag +gui, match:class ^(com\.obsproject\.Studio)$
windowrule = tag +gui, match:class gimp
windowrule = tag +gui, match:class ^.*(Nicotine)$
windowrule = tag +gui, match:class steam
windowrule = tag +gui, match:class xdg-desktop-portal-gtk
windowrule = tag +gui, match:class ^([Vv]irt.*)
windowrule = tag +gui, match:class filezilla

#Float
windowrule  {
    name = apply-video
    match:tag = video
    opacity = 1.0 override
    no_blur = on
    float = true
    center = on
    content = video
    max_size = 849 477
}

windowrule = float true, match:tag gui

# Sizes
# windowrule = max_size 849 477, match:tag img
windowrule = float true, match:tag img

# Opacity and blur
windowrule = opacity 1.0 override, no_blur on, match:tag img
windowrule = opacity 1.0 override, no_blur on, match:tag browser
windowrule = opacity 1.0 override, match:tag gui
windowrule = opacity 1.0 override, match:tag pdf
windowrule = opacity 1.0 override, match:class .*(KeePassXC)$
windowrule = opacity 1.0 override, match:title ^(Transmission)$
windowrule = opacity 1.0 override, match:class nwg-look

windowrule = match:class (pinentry-)(.*), stay_focused on   # Fix pinentry losing focus

# Workspace 1
windowrule = workspace 1, match:class firefox

# Worspace 3
windowrule = workspace 3, match:class brave-browser
windowrule = workspace 3, match:class librewolf

# Workspace 4
windowrule = workspace 4, match:class code
windowrule = workspace 4, match:class anki
windowrule = workspace 4, match:class ^([Vv]irt.*)

# Workspace 5
windowrule = workspace 5, match:class .*(KeePassXC)$
windowrule = workspace 5, match:class gcr-prompter

# Workspace 6
windowrule = workspace 6, match:class gimp
windowrule = workspace 6, match:class filezilla

# Workspace 7
windowrule = workspace 7, match:class ^(com\.obsproject\.Studio)$

# Workspace 8
windowrule = workspace 8 silent, match:class org.nicotine_plus.Nicotine
windowrule = workspace 8 silent float, match:class steam

# Workspace 10
windowrule = workspace 10 silent, match:title ^(Transmission)$
