# Tags
windowrule = tag +video, class:mpv

# Browser
windowrule = tag +browser, class:firefox-esr
windowrule = tag +browser, class:brave-browser

# GUI
windowrule = tag +gui, class:blueberry.py
windowrule = tag +gui, class:org.fcitx.fcitx5-config-qt
windowrule = tag +gui, class:org.pulseaudio.pavucontrol
windowrule = tag +gui, class:^(com\.obsproject\.Studio)$

#Float
windowrule = float, class:mpv
windowrule = center, class:mpv
windowrule = content video, class:mpv
windowrule = float, tag:gui

# Sizes
windowrule = maxsize 849 477, class:mpv

# Opacity and blur
windowrule = noblur, class:mpv
windowrule = opacity 1.0 override, tag:video
windowrule = noblur, tag:browser
windowrule = opacity 1.0 override, tag:browser
windowrule = opacity 1.0 override, tag:gui
windowrule = opacity 1.0 override, title:^(Transmission)$

# Workspaces

# Workspace 1
windowrule = workspace 1, class:firefox-esr

# Worspace 3
windowrule = workspace 3, class:brave-browser
windowrule = workspace 3, class:code

# Workspace 4
windowrule = workspace 4, class:gimp
windowrule = workspace 4, class:^(com\.obsproject\.Studio)$
windowrule = workspace 4, class:^(VirtualBox)

# Workspace 5
windowrule = workspace 5, class:org.keepassxc.KeePassXC

# Workspace 6
windowrule = workspace 6, class:filezilla

# Workspace 8
windowrule = workspace 8 silent, class:org.nicotine_plus.Nicotine
windowrule = workspace 8 silent float, class:steam

# Workspace 9
windowrule = workspace 9 silent, title:^(Transmission)$
