#!/bin/sh

# Current rice
read -r RICETHEME < "${HOME}"/.config/bspwm/.rice
#
# Set environment variables
export PATH="$HOME/.config/bspwm/src:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

$HOME/.config/x11/xinitrc
$HOME/.config/polybar/launch.sh

# Launch sxhkd daemon
pidof -q sxhkd || { sxhkd -c "${HOME}"/.config/bspwm/sxhkdrc & }

# Launch picom
pidof -q picom || { picom --config "${HOME}"/.config/bspwm/picom.conf & }

pgrep -x nm-applet || nm-applet &
pgrep -x redshift-gtk || redshift-gtk &
numlockx on &
fcitx5 -dr &

# Fix cursor
xsetroot -cursor_name left_ptr

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

# Set system vars for polybar
"$HOME"/.config/bspwm/src/SetSysVars

# Load current theme
"${HOME}"/.config/bspwm/rices/"${RICETHEME}"/Theme.sh
# Default 1 monitor with 6 workspaces
for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
    bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6' '7' '8' '9'
done

bspc config external_rules_command "${HOME}"/.local/bin/ExternalRules

### BSPWM config ###
bspc config window_gap                5
bspc config top_padding               30
bspc config bottom_padding            5
bspc config left_padding              3
bspc config right_padding             3
bspc config split_ratio               0.51
bspc config single_monocle            true
bspc config borderless_monocle        false
bspc config gapless_monocle           false

bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     false
bspc config pointer_motion_interval   5
bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

bspc rule -a scratch sticky=on state=floating focus=on

#BSPWM coloring
bspc config normal_border_color		"#928374"
bspc config active_border_color		"#282828"
bspc config focused_border_color	"#fb4934"
bspc config presel_feedback_color	"#98971a"
bspc config urgent_border_color 	"#cc241d"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
