# Animations for Dunst notifications.
	{
		match = "class_g = 'Dunst'";
		animations = (
		{
			triggers = ["close", "hide"];
			preset = "fly-out";	#-dunst-close-preset
			direction = "up";	#-dunst-close-direction
			duration = 0.2;
		},
		{
			triggers = ["open", "show"];
			preset = "fly-in";	#-dunst-open-preset
			direction = "up";	#-dunst-open-direction
			duration = 0.2;
		}
		)
	},
