#  ╔═╗╦╔═╗╔═╗╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗ - z0mbi3
#  ╠═╝║║  ║ ║║║║  ║  ║ ║║║║╠╣ ║║ ╦ - https://github.com/gh0stzk/dotfiles
#  ╩  ╩╚═╝╚═╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝ - My picom configuration

#################################
#             Shadows           #
#################################

shadow = true;

shadow-radius = 7;
shadow-opacity = .5
shadow-offset-x = -2;
shadow-offset-y = -1;
shadow-color = "#000000"

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
  "class_g = 'jgmenu'",
  "class_g = 'slop'",
  "class_g = 'Dunst'",
  "class_g = 'scratch'",
  "class_g = 'Spotify'",
  "class_g = 'retroarch'",
  "class_g = 'dmenu'",
  "class_g = 'fcitx'",
  "class_g = 'mozc'",
  "_GTK_FRAME_EXTENTS@:c",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];

#################################
#           Fading              #
#################################

fading = true;

fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5
no-fading-openclose = false
no-fading-destroyed-argb = false

fade-exclude = [
	"name = 'Eww - bar'",
    "class_g = 'slop'",
    "class_g = 'Polybar'",
    "class_g = 'scratch'"
];

#################################
#           Corners             #
#################################

corner-radius = 1

rounded-corners-exclude = [
  "window_type = 'dropdown_menu'",
  "window_type = 'popup_menu'",
  "window_type = 'popup'",
  "window_type = 'dock'",
  "class_g = 'Polybar'",
  "class_g = 'dmenu'",
  "class_g = 'mpv'",
];

#################################
#   Transparency / Opacity      #
#################################

inactive-opacity = 0.8;
inactive-opacity-override = true;

focus-exclude = [
    "class_g = 'maim'",
    "class_g = 'KeePassXC'",
    "class_g = 'Dunst'",
    "class_g = 'fcitx'",
    "class_g = 'Pcmanfm'"
];

opacity-rule = [
  "100:class_g = 'kitty'",
  "100:class_g = 'fcitx'"
];

#################################
#       General Settings        #
#################################

# Available backends "xrender" "glx" "egl" "xr_glx_hybrid"
backend = "xrender";

dithered-present = false;
vsync = true;

detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;

use-damage = true;
# xrender-sync-fence = false
# transparent-clipping = false

log-level = "error";

#################################
#             Rules             #
#################################

blur:

	{
		method = "gaussian";
		size = 10;
		deviation = 2.5;
	}

rules: (

	{
		blur-background = false;
		fade = true;
	},

	{
		match = "window_type = 'normal'";
		fade = true;	#-fade-switch
		shadow = true;	#-shadow-switch
	},

	{
		match = "window_type = 'dialog'";
		shadow = true;	#-shadow-switch
	},

	{
		match = "window_type = 'tooltip'";
		corner-radius = 0;
		opacity = 0.90;
	},

	{
		match = "window_type = 'dock'";
		corner-radius = 0;
		fade = true;
	},

@include "picom-animations.conf"

)

#################################
#          Wintypes             #
#################################

# wintypes:
# {
# normal =  { fade = true; shadow = false; }
# tooltip = { focus = true; shadow = false; }
# dock =  { fade = true; }
# utility = { shadow = false; }
# };
