[settings]
;https://github.com/jaagr/polybar/wiki/Configuration#application-settings
screenchange-reload = true

; Enables pseudo-transparency for the bar
; If set to true the bar can be transparent without a compositor.
pseudo-transparency = false
compositing-background = over
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

; Define fallback values used by all module formats
format-foreground = #FF0000
format-background = #00FF00

include-file = ~/.config/polybar/themes/colors/gruvbox.ini

[bar/cliffmain]
width = 100%
height = 33px
;previous value for radius was 10%
radius = 0
monitor = eDP1
monitor-strict = false
override-redirect = true
bottom = false
fixed-center = true
scroll-up = bspwm.next
scroll-down = bspwm.prev

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt
line-color = ${colors.foreground}

border-size = 0
border-color = ${colors.darkgreen}

padding-left = 1
padding-right = 1

module-margin-left = 1
module-margin-right = 1

offset-x = 0
offset-y = 0

separator = |
separator-foreground = ${colors.darkorange}

font-0 = "JetBrainsMono NF:style=Medium:size=10;2"
font-1 = "JetBrainsMono NF:style=Bold:size=10;2"
font-2 = "JetBrainsMono NF:size=19;5"
font-3 = "Noto Sans CJK JP:size=9;2"

modules-left = bspwm xwindow mpd
modules-center = date
modules-right = tray bluetooth pulseaudio backlight temperature battery

cursor-click = pointer
cursor-scroll = ns-resize


enable-ipc = false
wm-name = bspwm
locale = es_AR.UTF-8
wm-restack = bspwm

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.red}
label-active-underline= ${colors.darkgreen}
label-active-padding = 2

label-occupied = %name%
label-occupied-padding = 2

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %name%
label-empty-foreground = ${colors.gray}
label-empty-padding = 2

[module/xwindow]
type = internal/xwindow
format = <label>
label = %title%
label-maxlen = 25

format-foreground = ${colors.foreground}
format-background = ${colors.background}

[module/bspwm]
type = internal/bspwm
pin-workspaces = true
inline-mode = false
enable-click = true
enable-scroll = true
reverse-scroll = true

label-focused = %index%
label-focused-background = ${colors.background}
label-focused-underline = ${colors.darkblue}
label-focused-padding = 1

label-occupied = %index%
label-occupied-padding = 1
label-occupied-background = ${colors.background}
label-occupied-foreground = ${colors.darkblue}

label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty =

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = true
click-right = pavucontrol

format-volume = <ramp-volume> <label-volume>

label-volume = %percentage%%

format-muted = <label-muted>
label-muted = 󰝟
label-muted-foreground = ${colors.gray}
label-muted-background = ${colors.background}
label-muted-underline = ${colors.gray}

label-volume-underline = ${colors.darkyellow}
format-volume-foreground = ${colors.foreground}
format-volume-background = ${colors.background}

ramp-volume-0 = 󰕿
ramp-volume-0-underline = ${colors.volume-min}
ramp-volume-1 = 󰖀
ramp-volume-1-underline = ${colors.volume-med}
ramp-volume-2 = 󰕾
ramp-volume-2-underline = ${colors.volume-max}

[module/tray]
type = internal/tray

format-margin = 8px
tray-spacing = 8px

format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-underline = ${colors.green}

[module/date]
type = internal/date
interval = 1.0

date = "%d/%m/%Y"
time = %H:%M
label = %date% %time%

format-prefix = " "
format-prefix-foreground = ${colors.foreground}
format-underline = ${colors.darkgreen}
format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-sep-foreground = ${color.darkorange}

click-right = st -e calcurse

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 100
format-charging = 󰂄 <label-charging>
label-charging = %percentage%%
format-charging-padding = 1
format-charging-foreground = ${colors.foreground}
format-charging-background = ${colors.background}
format-charging-underline = ${colors.orange}

format-discharging = <ramp-capacity> <label-discharging>
label-discharging = %percentage%%
format-discharging-underline = ${colors.darkpurple}
format-discharging-foreground = ${colors.foreground}
format-discharging-background = ${colors.background}

format-full-prefix = "  "
format-full-prefix-foreground = ${colors.green}
format-full-underline = ${colors.darkgreen}
format-full-foreground = ${colors.foreground}
format-full-background = ${colors.background}

ramp-capacity-0 = " "
ramp-capacity-1 = " "
ramp-capacity-2 = " "
ramp-capacity-3 = " "
ramp-capacity-4 = " "
ramp-capacity-0-foreground = ${colors.alert}
ramp-capacity-1-foreground = ${colors.darkyellow}
ramp-capacity-2-foreground = ${colors.darkblue}
ramp-capacity-3-foreground = ${colors.blue}
ramp-capacity-4-foreground = ${colors.aqua}
format-discharging-padding = 1

[module/backlight]
type = internal/backlight

; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
card = intel_backlight

format = <ramp>
format-foreground = ${colors.foreground}
format-background = ${colors.background}

; Available tags:
;   <label> (default)
;   <ramp>
;   <bar>

; Only applies if <ramp> is used
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
ramp-5 = 

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth.sh
interval = 2
click-left = exec blueberry
click-right = exec ~/.config/polybar/scripts/toggle_bluetooth.sh
format-padding = 1
format-background = ${colors.background}
format-foreground = ${colors.foreground}
format-underline = ${colors.darkblue}

[module/temperature]
type = internal/temperature

; Seconds to sleep between updates
; Default: 1
interval = 0.5

; Thermal zone to use
; To list all the zone types, run
; $ for i in /sys/class/thermal/thermal_zone*; do echo "$i: $(<$i/type)"; done
; Default: 0
thermal-zone = 0

; Select thermal zone by name
; The name has to match the contents of /sys/class/thermal/thermal_zone*/type
; for the desired thermal zone.
; New in version 3.7.0
; Default: ""
zone-type = x86_pkg_temp

; Full path of temperature sysfs path
; Use `sensors` to find preferred temperature source, then run
; $ for i in /sys/class/hwmon/hwmon*/temp*_input; do echo "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*})) $(readlink -f $i)"; done
; to find path to desired file
; Default reverts to thermal zone setting
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input

; Base temperature for where to start the ramp (in degrees celsius)
; Default: 0
base-temperature = 20

; Threshold temperature to display warning label (in degrees celsius)
; Default: 80
warn-temperature = 60

format = <ramp> <label>
format-warn = <ramp> <label-warn>
label = TEMP %temperature-c%
label-warn = TEMP %temperature-c%
label-warn-foreground = ${colors.foreground}
label-warn-background = ${colors.background}
label-warn-underline = ${colors.red}

ramp-0 = A
ramp-1 = B
ramp-2 = C
ramp-foreground = ${colors.foreground}
ramp-background = ${colors.background}

format-foreground = ${colors.foreground}
format-background = ${colors.background}

label-underline = ${colors.darkyellow}

[module/mpd]
type = internal/mpd

; Host where mpd is running (either ip or domain name)
; Can also be the full path to a unix socket where mpd is running.
host = 127.0.0.1
port = 6600

; Seconds to sleep between progressbar/song timer sync
; Default: 1
interval = 2

; More formatting
format-online = <toggle> <bar-progress> <label-time> <label-song>

; Default: %artist% - %title%
label-song = %artist% - %title%
label-song-maxlen = 40
label-song-ellipsis = true

; Available tokens:
;   %elapsed%
;   %total%
; Default: %elapsed% / %total%
;label-time = %elapsed% / %total%

; Available tokens:
;   None
label-offline = 🎜 mpd is offline

; Only applies if <icon-X> is used
icon-play = ⏵
icon-pause = ⏸
icon-stop = ⏹
icon-prev = ⏮
icon-next = ⏭
icon-seekb = ⏪
icon-seekf = ⏩
icon-random = 🔀
icon-repeat = 🔁
icon-repeatone = 🔂
icon-single = 🔂
icon-consume = ✀

; Used to display the state of random/repeat/repeatone/single
; Only applies if <icon-[random|repeat|repeatone|single]> is used
toggle-on-foreground = ${colors.foreground}
toggle-off-foreground = ${colors.gray}

format-online-background = ${colors.background}
format-online-foreground = ${colors.foreground}

; Only applies if <bar-progress> is used
bar-progress-width = 10
bar-progress-indicator-background = ${colors.background}
bar-progress-indicator-foreground = ${colors.foreground}
bar-progress-indicator = |
bar-progress-fill = ─
bar-progress-fill-background = ${colors.background}
bar-progress-fill-foreground = ${colors.yellow}
bar-progress-empty = ─
bar-progress-empty-background = ${colors.background}
bar-progress-empty-foreground = ${colors.yellow}
